# Generated by Django 4.0.1 on 2022-02-22 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=20)),
                ('n_callees', models.IntegerField()),
                ('pais', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='personas',
            name='domicilio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personasApp.domicilio'),
            preserve_default=False,
        ),
    ]
